### ISSUE TITLE
Follow Fluentd's naming conventions

### ISSUE THREAD

**Issue by kiyoto** [car-throttle/fluent-plugin-keen#1]
Typically, Fluentd plugins are named as `fluent-plugin-PLUGIN_NAME`. For this plugin, it's probably a good idea to rename it as `fluent-plugin-keen` if it's not too late. That way, it will get picked up by www.fluentd.org/plugins/all

**Comment by jdrydn** [comment]
:+1: Cheers for that, it's fairly early days so it's not too much trouble! Just a few links here and there to update!
